/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package skillforge;

import com.google.gson.reflect.TypeToken;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.List;

public class InstructorFrame extends javax.swing.JFrame {

    private java.awt.CardLayout cardLayout;
    /**
     * Creates new form InstructorFrame
     */
    private LoginFrame loginFrame;
    private Instructor currentInstructor;
    private InstructorManager instructorManager;
    private CourseManagment courseManager;
    private StudentManager studentManager;
    private UserDatabaseManager userDb;
    private Course selectedCourse;

    public InstructorFrame(LoginFrame frame, Instructor instructor) {
        initComponents();
        this.loginFrame = frame; // save reference
        this.currentInstructor = instructor;
        this.setLocationRelativeTo(null);  // center the frame
        cardLayout = (java.awt.CardLayout) getContentPane().getLayout();
        initializeBackend();
        jTable2.getSelectionModel().addListSelectionListener(e -> {
    if (!e.getValueIsAdjusting()) {
        int selectedRow = jTable2.getSelectedRow();
        if (selectedRow != -1 && selectedCourse != null && selectedRow < selectedCourse.getLessons().size()) {
            Lesson lesson = selectedCourse.getLessons().get(selectedRow);
            
            LessonID.setText(lesson.getLessonID());
            Lessontitle.setText(lesson.getLessonTitle());
            Lessoncontent.setText(lesson.getLessonContent());
            
            // Populate resources field
            if (lesson.getOptionalResources() != null && !lesson.getOptionalResources().isEmpty()) {
                String resourcesString = String.join(", ", lesson.getOptionalResources());
                LessonResources.setText(resourcesString);
            } else {
                LessonResources.setText("");
            }
        }
    }
});
    }

    private void initializeBackend() {
        courseManager = new CourseManagment(
                "courses.json",
                new TypeToken<Course>() {
                }.getType()
        );

        userDb = new UserDatabaseManager();
        studentManager = new StudentManager(userDb, courseManager);

        instructorManager = new InstructorManager(
                "users.json",
                "courses.json",
                new TypeToken<Instructor>() {
                }.getType(),
                new TypeToken<Course>() {
                }.getType()
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        EditCoursePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        DeletePanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        ManageLessonsPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        LessonID = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Lessontitle = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Lessoncontent = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        LessonResources = new javax.swing.JTextField();
        ViewStudents = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton8 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        LessonPanel = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        AddLessonPanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        LessonIDText = new javax.swing.JTextField();
        LessonTitleText = new javax.swing.JTextField();
        LessonContentText = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        ResourcesText = new javax.swing.JTextField();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        EditCoursePanel.setBackground(new java.awt.Color(204, 204, 255));
        EditCoursePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Edit Course");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Enter Course ID:");

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Course ID", "Course Title", "Course Description", "Course Instructor ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 153, 255));
        jButton2.setText("Confirm ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(153, 153, 255));
        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EditCoursePanelLayout = new javax.swing.GroupLayout(EditCoursePanel);
        EditCoursePanel.setLayout(EditCoursePanelLayout);
        EditCoursePanelLayout.setHorizontalGroup(
            EditCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(EditCoursePanelLayout.createSequentialGroup()
                .addGroup(EditCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EditCoursePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(EditCoursePanelLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jButton3)
                        .addGap(0, 103, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(EditCoursePanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(28, 28, 28))
        );
        EditCoursePanelLayout.setVerticalGroup(
            EditCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditCoursePanelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EditCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(EditCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        getContentPane().add(EditCoursePanel, "EditCourseCard");

        DeletePanel.setBackground(new java.awt.Color(204, 204, 255));
        DeletePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Delete Course");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Enter Course ID:");

        jButton4.setBackground(new java.awt.Color(153, 153, 255));
        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(153, 153, 255));
        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DeletePanelLayout = new javax.swing.GroupLayout(DeletePanel);
        DeletePanel.setLayout(DeletePanelLayout);
        DeletePanelLayout.setHorizontalGroup(
            DeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeletePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(DeletePanelLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(DeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(DeletePanelLayout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4))
                    .addGroup(DeletePanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 146, Short.MAX_VALUE))
        );
        DeletePanelLayout.setVerticalGroup(
            DeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeletePanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addGap(155, 155, 155)
                .addGroup(DeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(99, 99, 99)
                .addGroup(DeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 105, Short.MAX_VALUE))
        );

        getContentPane().add(DeletePanel, "DeleteCourseCard");

        ManageLessonsPanel.setBackground(new java.awt.Color(204, 204, 255));
        ManageLessonsPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Edit Lesson");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Lesson ID", "Lesson Title", "Lesson Content", "Lesson Resurces"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Lesson Details");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Lesson ID:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Lesson Title:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Lesson Content:");

        jButton6.setBackground(new java.awt.Color(153, 153, 255));
        jButton6.setText("Save");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(153, 153, 255));
        jButton7.setText("Back");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(153, 153, 255));
        jButton13.setText("Delete");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Resources(separated by commas):");

        javax.swing.GroupLayout ManageLessonsPanelLayout = new javax.swing.GroupLayout(ManageLessonsPanel);
        ManageLessonsPanel.setLayout(ManageLessonsPanelLayout);
        ManageLessonsPanelLayout.setHorizontalGroup(
            ManageLessonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ManageLessonsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ManageLessonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ManageLessonsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ManageLessonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ManageLessonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ManageLessonsPanelLayout.createSequentialGroup()
                            .addGroup(ManageLessonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(76, 76, 76))
                        .addGroup(ManageLessonsPanelLayout.createSequentialGroup()
                            .addComponent(jButton7)
                            .addGap(150, 150, 150)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ManageLessonsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(36, 36, 36)))
                .addGroup(ManageLessonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LessonID)
                    .addComponent(Lessontitle)
                    .addComponent(Lessoncontent, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addGroup(ManageLessonsPanelLayout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addGap(18, 18, 18)
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                    .addComponent(LessonResources))
                .addGap(154, 154, 154))
        );
        ManageLessonsPanelLayout.setVerticalGroup(
            ManageLessonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageLessonsPanelLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ManageLessonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ManageLessonsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(ManageLessonsPanelLayout.createSequentialGroup()
                        .addComponent(LessonID, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lessontitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lessoncontent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addGroup(ManageLessonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LessonResources, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))))
                .addGroup(ManageLessonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton13))
                .addGap(7, 7, 7))
        );

        getContentPane().add(ManageLessonsPanel, "ManageLessonsCard");

        ViewStudents.setBackground(new java.awt.Color(204, 204, 255));
        ViewStudents.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel10.setBackground(new java.awt.Color(204, 204, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText(" Enrolled Students");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Student ID", "Student Name", "Student Progress"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jButton8.setBackground(new java.awt.Color(153, 153, 255));
        jButton8.setText("Back");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel11.setText("Select the student you want to remove");

        jButton9.setBackground(new java.awt.Color(153, 153, 255));
        jButton9.setText("Remove");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ViewStudentsLayout = new javax.swing.GroupLayout(ViewStudents);
        ViewStudents.setLayout(ViewStudentsLayout);
        ViewStudentsLayout.setHorizontalGroup(
            ViewStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ViewStudentsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ViewStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewStudentsLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(ViewStudentsLayout.createSequentialGroup()
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton9)
                        .addGap(98, 98, 98))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewStudentsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        ViewStudentsLayout.setVerticalGroup(
            ViewStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewStudentsLayout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(ViewStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton9))
                .addContainerGap())
        );

        getContentPane().add(ViewStudents, "ViewStudentsCard");

        LessonPanel.setBackground(new java.awt.Color(204, 204, 255));
        LessonPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton10.setBackground(new java.awt.Color(153, 153, 255));
        jButton10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton10.setText("Add Lesson");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(153, 153, 255));
        jButton11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton11.setText("Edit Existing Lessons");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Manage Lessons");

        jButton12.setBackground(new java.awt.Color(153, 153, 255));
        jButton12.setText("Back");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LessonPanelLayout = new javax.swing.GroupLayout(LessonPanel);
        LessonPanel.setLayout(LessonPanelLayout);
        LessonPanelLayout.setHorizontalGroup(
            LessonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LessonPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(LessonPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jButton12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LessonPanelLayout.setVerticalGroup(
            LessonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LessonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                .addGroup(LessonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(144, 144, 144)
                .addComponent(jButton12)
                .addGap(24, 24, 24))
        );

        getContentPane().add(LessonPanel, "LessonCard");

        AddLessonPanel.setBackground(new java.awt.Color(204, 204, 255));
        AddLessonPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Add Lesson");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Lesson ID: ");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("Lesson Title:");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("Lesson Content:");
        jLabel16.setToolTipText("");

        jButton14.setBackground(new java.awt.Color(153, 153, 255));
        jButton14.setText("Add");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setBackground(new java.awt.Color(153, 153, 255));
        jButton15.setText("Back");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Lesson Resources (separated by commas):");

        javax.swing.GroupLayout AddLessonPanelLayout = new javax.swing.GroupLayout(AddLessonPanel);
        AddLessonPanel.setLayout(AddLessonPanelLayout);
        AddLessonPanelLayout.setHorizontalGroup(
            AddLessonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(AddLessonPanelLayout.createSequentialGroup()
                .addGroup(AddLessonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(AddLessonPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButton15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton14))
                    .addGroup(AddLessonPanelLayout.createSequentialGroup()
                        .addGroup(AddLessonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddLessonPanelLayout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addGroup(AddLessonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(126, 126, 126))
                            .addGroup(AddLessonPanelLayout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jLabel18)
                                .addGap(48, 48, 48)))
                        .addGroup(AddLessonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LessonIDText)
                            .addComponent(LessonTitleText)
                            .addComponent(LessonContentText)
                            .addComponent(ResourcesText, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        AddLessonPanelLayout.setVerticalGroup(
            AddLessonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddLessonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(28, 28, 28)
                .addGroup(AddLessonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LessonIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(AddLessonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LessonTitleText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(AddLessonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(LessonContentText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(AddLessonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(ResourcesText, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(AddLessonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton14)
                    .addComponent(jButton15))
                .addGap(19, 19, 19))
        );

        getContentPane().add(AddLessonPanel, "AddLessonCard");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        loginFrame.showPanel("HomeCard"); // switch to the desired panel
        loginFrame.setVisible(true);       // show the main frame
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        loginFrame.showPanel("HomeCard");
        loginFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        loginFrame.showPanel("HomeCard"); // switch to the desired panel
        loginFrame.setVisible(true);       // show the main frame
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        loginFrame.showPanel("HomeCard"); // switch to the desired panel
        loginFrame.setVisible(true);       // show the main frame
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
if (selectedCourse == null) {
        JOptionPane.showMessageDialog(this,
                "No course selected!",
                "Error",
                JOptionPane.ERROR_MESSAGE);
        return;
    }

    int selectedRow = jTable3.getSelectedRow();

    if (selectedRow < 0) {
        JOptionPane.showMessageDialog(this,
                "Please select a student from the table!",
                "Selection Required",
                JOptionPane.WARNING_MESSAGE);
        return;
    }

    DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
    String studentId = model.getValueAt(selectedRow, 0).toString();
    String studentName = model.getValueAt(selectedRow, 1).toString();

    int result = JOptionPane.showConfirmDialog(
            this,
            "Remove " + studentName + " from " + selectedCourse.getCourseTitle() + "?",
            "Confirm Removal",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
    );

    if (result == JOptionPane.YES_OPTION) {
        boolean success = courseManager.removeStudent(
                selectedCourse.getCourseID(),
                studentId
        );

        if (success) {
            JOptionPane.showMessageDialog(this,
                    studentName + " removed successfully!",
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE);

            // Refresh student table
            loadEnrolledStudents(selectedCourse.getCourseID());
        } else {
            JOptionPane.showMessageDialog(this,
                    "Failed to remove student!",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String courseId = jTextField3.getText().trim();

        if (courseId.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Please enter a Course ID",
                    "Input Required",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        Course course = courseManager.getCourseByID(courseId);

        if (course == null) {
            JOptionPane.showMessageDialog(this,
                    "Course not found!",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!course.getInstructorID().equals(currentInstructor.getUserId())) {
            JOptionPane.showMessageDialog(this,
                    "You can only delete your own courses!",
                    "Access Denied",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        int result = JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to delete: " + course.getCourseTitle() + "?",
                "Confirm Delete",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
        );

        if (result == JOptionPane.YES_OPTION) {
            boolean success = courseManager.deleteById(courseId);

            if (success) {
                currentInstructor.removeCreatedCourse(courseId);
                userDb.update(currentInstructor.getUserId(), currentInstructor);

                JOptionPane.showMessageDialog(this,
                        "Course deleted successfully!",
                        "Success",
                        JOptionPane.INFORMATION_MESSAGE);

                jTextField3.setText("");
            } else {
                JOptionPane.showMessageDialog(this,
                        "Failed to delete course!",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(selectedCourse == null){
            JOptionPane.showMessageDialog(this, "please select a course first", "No Course selected", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String lessonID = LessonID.getText().trim();
        String lessonTitle = Lessontitle.getText().trim();
        String lessonContent = Lessoncontent.getText().trim();
        String resources = LessonResources.getText().trim();
        
        if(lessonID.isEmpty() || lessonTitle.isEmpty() || lessonContent.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please fill in Lesson Id, title and content", "validation error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(resources.isEmpty()){
            JOptionPane.showMessageDialog(this, "you can not leave the resources field empty", "validation error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Lesson lesson = selectedCourse.getLesson(lessonID);
        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
if (selectedCourse == null) {
        JOptionPane.showMessageDialog(this,
                "Please search for a course first!",
                "Error",
                JOptionPane.ERROR_MESSAGE);
        return;
    }

    // CRITICAL FIX: Stop any active cell editing first
    if (jTable1.isEditing()) {
        jTable1.getCellEditor().stopCellEditing();
    }
    
    // Give the table a moment to update its model
    try {
        Thread.sleep(100);
    } catch (InterruptedException e) {
        // Ignore
    }

    int result = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to save the changes?",
            "Confirm Saving",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
    );

    if (result == JOptionPane.YES_OPTION) {
        try {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            if (model.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this,
                        "No course to update!",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            Object titleObj = model.getValueAt(0, 1);
            Object descObj = model.getValueAt(0, 2);
            
            if (titleObj == null || descObj == null) {
                JOptionPane.showMessageDialog(this,
                        "Title and Description cannot be empty!",
                        "Validation Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            String newTitle = titleObj.toString();
            String newDescription = descObj.toString();

            System.out.println("Saving - Title: " + newTitle);
            System.out.println("Saving - Description: " + newDescription);

            boolean success = instructorManager.editCourse(
                    selectedCourse.getCourseID(),
                    newTitle,
                    newDescription
            );

            if (success) {
                JOptionPane.showMessageDialog(this,
                        "Course updated successfully!",
                        "Success",
                        JOptionPane.INFORMATION_MESSAGE);

                jTextField1.setText("");
                model.setRowCount(0);
                selectedCourse = null;
            } else {
                JOptionPane.showMessageDialog(this,
                        "Failed to update course. Check console for validation errors.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    } else {
        JOptionPane.showMessageDialog(this,
                "No changes saved",
                "Cancelled",
                JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String courseId = jTextField1.getText().trim();

        if (courseId.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Please enter a Course ID",
                    "Input Required",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        Course course = courseManager.getCourseByID(courseId);

        if (course == null) {
            JOptionPane.showMessageDialog(this,
                    "Course not found!",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!course.getInstructorID().equals(currentInstructor.getUserId())) {
            JOptionPane.showMessageDialog(this,
                    "You can only edit your own courses!",
                    "Access Denied",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        model.addRow(new Object[]{
            course.getCourseID(),
            course.getCourseTitle(),
            course.getCourseDescription(),
            course.getInstructorID()
        });

        selectedCourse = course;

        JOptionPane.showMessageDialog(this,
                "Course found! You can now edit the table and click Confirm.",
                "Success",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        int selectedRow = jTable2.getSelectedRow();
        if (selectedRow >= 0) {
            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            LessonID.setText(model.getValueAt(selectedRow, 0).toString());
            Lessontitle.setText(model.getValueAt(selectedRow, 1).toString());
            Lessoncontent.setText(model.getValueAt(selectedRow, 2).toString());
        }
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        if (selectedCourse == null) {
            JOptionPane.showMessageDialog(this,
                "Please select a course first",
                "No Course Selected",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        LessonPanel.setVisible(false);
        ManageLessonsPanel.setVisible(true);
        //loadCourseLessons(selectedCourse.getCourseID());
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        loginFrame.showPanel("HomeCard"); // switch to the desired panel
        loginFrame.setVisible(true);       // show the main frame
        this.dispose();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        loginFrame.showPanel("HomeCard"); // switch to the desired panel
        loginFrame.setVisible(true);       // show the main frame
        this.dispose();
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        selectedCourse = askForCourseId();
        if(selectedCourse == null){
            return;
        }
        LessonPanel.setVisible(false);
        AddLessonPanel.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        if (selectedCourse == null) {
        JOptionPane.showMessageDialog(this,
            "Please select a course first",
            "No Course Selected",
            JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    String courseId = selectedCourse.getCourseID();
    String lessonId = LessonIDText.getText().trim();
    String lessonTitle = LessonTitleText.getText().trim();
    String lessonContent = LessonContentText.getText().trim();
    String resources = ResourcesText.getText().trim();
    
    if(lessonId.isEmpty() || lessonTitle.isEmpty() || lessonContent.isEmpty()) {
        JOptionPane.showMessageDialog(this,
            "Please fill in Lesson ID, Title, and Content!",
            "Validation Error",
            JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    if(resources.isEmpty()){
        JOptionPane.showMessageDialog(this,
            "You cannot leave resources field empty!",
            "Validation Error",
            JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    String[] items = resources.split(",");
    ArrayList<String> list = new ArrayList<>();
    for(int i = 0; i < items.length; i++){
        String item = items[i].trim();
        if (!item.isEmpty()) {
            list.add(item);
        }
    }
    
    boolean result1 = instructorManager.addLesson(courseId, lessonId, lessonTitle, lessonContent);
    
    if(result1){
        selectedCourse = courseManager.getCourseByID(courseId);
        Lesson addedLesson = selectedCourse.getLesson(lessonId);
    
        if (addedLesson != null) {
            // Set the resources using the setter
            addedLesson.setOptionalResources(list);
        
            // Save the updated course back to JSON
            courseManager.update(courseId, selectedCourse);
        
            JOptionPane.showMessageDialog(this,
                "Lesson added successfully!",
                "Success",
                JOptionPane.INFORMATION_MESSAGE);
        
            // Clear the fields
            LessonIDText.setText("");
            LessonTitleText.setText("");
            LessonContentText.setText("");
            ResourcesText.setText("");
            
        } else {
            JOptionPane.showMessageDialog(this,
                "An error occurred, could not add lesson resources",
                "Adding Failed",
                JOptionPane.ERROR_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(this,
            "An error occurred, could not add lesson. Lesson ID might already exist.",
            "Adding Failed",
            JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButton14ActionPerformed

    
    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        if (selectedCourse == null) {
            JOptionPane.showMessageDialog(this,
            "Please select a course first",
            "No Course Selected",
            JOptionPane.WARNING_MESSAGE);
            return;
        }
        String lessonId = LessonID.getText();
        int result1 = JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to delete this lesson? ",
                "Confirm Delete",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
        );

        if (result1 == JOptionPane.YES_OPTION) {
            boolean result = instructorManager.deleteLesson(selectedCourse.getCourseID(), lessonId.trim());
        if(result){
                JOptionPane.showMessageDialog(this,
                    "lesson deleted successfully",
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(this,
                    "An error occured could not delete lesson",
                    "deleting failed",
                    JOptionPane.ERROR_MESSAGE);
            }        
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    public void showPanel(String panelKey) {
        cardLayout.show(getContentPane(), panelKey);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddLessonPanel;
    private javax.swing.JPanel DeletePanel;
    private javax.swing.JPanel EditCoursePanel;
    private javax.swing.JTextField LessonContentText;
    private javax.swing.JTextField LessonID;
    private javax.swing.JTextField LessonIDText;
    private javax.swing.JPanel LessonPanel;
    private javax.swing.JTextField LessonResources;
    private javax.swing.JTextField LessonTitleText;
    private javax.swing.JTextField Lessoncontent;
    private javax.swing.JTextField Lessontitle;
    private javax.swing.JPanel ManageLessonsPanel;
    private javax.swing.JTextField ResourcesText;
    private javax.swing.JPanel ViewStudents;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
public void loadCourseLessons(String courseId) {
    Course course = courseManager.getCourseByID(courseId);
    if (course == null) {
        JOptionPane.showMessageDialog(this, "Course not found!");
        return;
    }
    selectedCourse = course;
    DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
    model.setRowCount(0);
    for (Lesson lesson : course.getLessons()) {
        // Convert resources ArrayList to a string
        String resourcesString = "";
        if (lesson.getOptionalResources() != null && !lesson.getOptionalResources().isEmpty()) {
            resourcesString = String.join(", ", lesson.getOptionalResources());
        }
        
        model.addRow(new Object[]{
            lesson.getLessonID(),
            lesson.getLessonTitle(),
            lesson.getLessonContent(),
            resourcesString  // Add resources column
        });
    }
}

    public void loadEnrolledStudents(String courseId) {
Course course = courseManager.getCourseByID(courseId);

    if (course == null) {
        return;
    }

    selectedCourse = course;
    
    // Re-fetch students to ensure we have latest data
    ArrayList<Student> students = course.getStudents();

    DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
    model.setRowCount(0);

    System.out.println("Loading students for course: " + courseId);
    System.out.println("Total students enrolled: " + students.size());

    for (Student student : students) {
        // Get fresh student data from database
        Student freshStudent = userDb.getStudentById(student.getUserId());
        
        if (freshStudent == null) {
            freshStudent = student; // Fallback to course's student reference
        }
        
        List<String> completedLessons = studentManager.getCompletedLessons(freshStudent, course);
        int totalLessons = course.getLessons().size();
        
        String progress = completedLessons.size() + "/" + totalLessons;
        
        System.out.println("Student: " + freshStudent.getUsername() + 
                         " - Progress: " + progress);

        model.addRow(new Object[]{
            freshStudent.getUserId(),
            freshStudent.getUsername(),
            progress
        });
    }
    
    System.out.println("Table loaded with " + model.getRowCount() + " rows");
    }
    
    public Course askForCourseId() {
    String courseId = JOptionPane.showInputDialog(
        null,
        "Please enter the Course ID:",
        "Enter Course ID",
        JOptionPane.QUESTION_MESSAGE
    );

    // If user pressed Cancel → return null
    if (courseId == null || courseId.trim().isEmpty()) {
        JOptionPane.showMessageDialog(
            null,
            "Operation cancelled or invalid Course ID.",
            "Cancelled",
            JOptionPane.WARNING_MESSAGE
        );
        return null;
    }

    return courseManager.getCourseByID(courseId);
}
}

